"""
Django settings for school project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import pymysql
from dotenv import load_dotenv

# Используем PyMySQL вместо mysqlclient (не требует компиляции C-расширений)
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загружаем переменные окружения из .env файла в директории проекта
env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "unsafe-dev-key-change-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'accounts',
    'sk',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'school.middleware.RequestLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'school.urls'

# CORS настройки
cors_origins_env = os.getenv("CORS_ORIGINS", "")
# Проверяем, есть ли .env файл (если SECRET_KEY не задан, значит скорее всего dev режим)
has_env_file = os.path.exists(env_path)
# В dev режиме (DEBUG=True или нет .env файла) добавляем localhost:5173 по умолчанию
if (DEBUG or not has_env_file) and not cors_origins_env:
    # В dev режиме, если CORS_ORIGINS не задан, разрешаем localhost:5173
    CORS_ALLOWED_ORIGINS = ['http://localhost:5173', 'http://127.0.0.1:5173']
elif cors_origins_env:
    # Если CORS_ORIGINS задан в .env, используем его
    CORS_ALLOWED_ORIGINS = [o.strip() for o in cors_origins_env.split(",") if o.strip()]
else:
    # Fallback - пустой список (будет ошибка, но это лучше чем разрешить все)
    CORS_ALLOWED_ORIGINS = []

if os.getenv("CSRF_TRUSTED_ORIGINS", "").strip():
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]
elif DEBUG or not has_env_file:
    CSRF_TRUSTED_ORIGINS = ['http://localhost:5173', 'http://127.0.0.1:5173']
else:
    CSRF_TRUSTED_ORIGINS = []

CORS_ALLOW_CREDENTIALS = True

# Разрешаем все необходимые заголовки для JWT и других запросов
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Разрешаем все методы
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.authentication.CookieJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

AUTH_COOKIE_ACCESS_NAME = os.getenv("AUTH_COOKIE_ACCESS_NAME", "access_token")
AUTH_COOKIE_REFRESH_NAME = os.getenv("AUTH_COOKIE_REFRESH_NAME", "refresh_token")
AUTH_COOKIE_SESSION_NAME = os.getenv("AUTH_COOKIE_SESSION_NAME", "auth_session")
AUTH_COOKIE_PATH = os.getenv("AUTH_COOKIE_PATH", "/")
AUTH_COOKIE_SAMESITE = os.getenv("AUTH_COOKIE_SAMESITE", "Lax")
AUTH_COOKIE_SECURE = os.getenv("AUTH_COOKIE_SECURE", "False") == "True"

CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", str(AUTH_COOKIE_SECURE)) == "True"
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", AUTH_COOKIE_SAMESITE)
CSRF_COOKIE_PATH = os.getenv("CSRF_COOKIE_PATH", "/")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("JWT_ACCESS_LIFETIME_MINUTES", "15"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("JWT_REFRESH_LIFETIME_DAYS", "30"))),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DB_NAME", "flare"),
        'USER': os.getenv("DB_USER", "flare_user"),
        'PASSWORD': os.getenv("DB_PASSWORD", ""),
        'HOST': os.getenv("DB_HOST", "127.0.0.1"),
        'PORT': os.getenv("DB_PORT", "3306"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Ограничения на размер входящих запросов и файлов
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DATA_UPLOAD_MAX_MEMORY_SIZE", str(8 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("FILE_UPLOAD_MAX_MEMORY_SIZE", str(8 * 1024 * 1024)))

AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:login'   
LOGOUT_REDIRECT_URL = 'accounts:login'


ROOT_ADMIN_EMAIL = os.getenv("ROOT_ADMIN_EMAIL", "admin@example.com")

# ЮKassa
YOOKASSA_API_URL = os.getenv("YOOKASSA_API_URL", "https://api.yookassa.ru/v3")
YOOKASSA_SHOP_ID = os.getenv("YOOKASSA_SHOP_ID", "")
YOOKASSA_SECRET_KEY = os.getenv("YOOKASSA_SECRET_KEY", "")
YOOKASSA_RETURN_URL_SUCCESS = os.getenv("YOOKASSA_RETURN_URL_SUCCESS", "https://flare-school.ru/payment/success")
YOOKASSA_RETURN_URL_CANCEL = os.getenv("YOOKASSA_RETURN_URL_CANCEL", "https://flare-school.ru/payment/cancel")
YOOKASSA_VAT_CODE = int(os.getenv("YOOKASSA_VAT_CODE", "1"))

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_NOTIFICATIONS_CHAT_ID = os.getenv("TELEGRAM_NOTIFICATIONS_CHAT_ID", "")
TELEGRAM_NOTIFICATIONS_TIMEOUT_SECONDS = int(os.getenv("TELEGRAM_NOTIFICATIONS_TIMEOUT_SECONDS", "10"))

# Белый список email'ов для создания админов через AdminLoginAPI
# Первые 2 из этого списка могут стать суперпользователями
ADMIN_SEED_EMAILS = [
    e.strip() for e in os.getenv(
        "ADMIN_SEED_EMAILS",
        ROOT_ADMIN_EMAIL
    ).split(",") if e.strip()
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(parents=True, exist_ok=True)


def _build_file_handler(filename, level, backup_count):
    if DEBUG and os.name == 'nt':
        return {
            'level': level,
            'class': 'logging.FileHandler',
            'filename': str(LOG_DIR / filename),
            'encoding': 'utf-8',
            'formatter': 'backend_json',
            'filters': ['request_context'],
        }

    return {
        'level': level,
        'class': 'logging.handlers.TimedRotatingFileHandler',
        'filename': str(LOG_DIR / filename),
        'when': 'midnight',
        'interval': 1,
        'backupCount': backup_count,
        'encoding': 'utf-8',
        'formatter': 'backend_json',
        'filters': ['request_context'],
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_context': {
            '()': 'school.logging_utils.RequestContextFilter',
        },
    },
    'formatters': {
        'backend_json': {
            '()': 'school.logging_utils.StructuredJSONFormatter',
        },
    },
    'handlers': {
        'backend_file': _build_file_handler('backend.log', 'INFO', 3),
        'backend_error_file': _build_file_handler('backend_errors.log', 'ERROR', 14),
    },
    'root': {
        'handlers': ['backend_file', 'backend_error_file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['backend_file', 'backend_error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['backend_file', 'backend_error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'school.request': {
            'handlers': ['backend_file', 'backend_error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'school.auth': {
            'handlers': ['backend_file', 'backend_error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'school.security': {
            'handlers': ['backend_file', 'backend_error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'school.error': {
            'handlers': ['backend_file', 'backend_error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
